using Tsumiki.Models.Foundation;

namespace Tsumiki.Commons
{
    /// <summary>
    /// 言語ごとの文言表
    /// </summary>
    /// <remarks>
    /// <see cref="Messages"/> から引く<br/>
    /// 言語を増やすときは、その言語の辞書をここに足して <see cref="Get_辞書"/> に繋ぐだけでよい<br/>
    /// 訳が無い ID は英語にそのまま落ちるので、部分的に訳した状態でも表示が壊れない
    /// </remarks>
    internal static class MessageCatalog
    {
        #region 定数

        /// <summary>
        /// 英語
        /// </summary>
        private static readonly Dictionary<メッセージID, string> _英語 = new()
        {
            [メッセージID.デブルーイングラフの要約] = "[Debug] Exact de Bruijn unitig graph: {0} directed edge(s), {1} branching vertex(es) out of {2}",
            [メッセージID.先読みで解決した分岐数] = "[Debug] Beam-search lookahead resolved {0} additional junction(s) that mutual uniqueness could not decide",
            [メッセージID.GFA出力完了] = "[Info] Wrote unitig graph to {0} (GFA1)",
            [メッセージID.分岐選択の重み内訳] = "[Debug] Branch selection weights: {0} single-read adjacency pair(s) + {1} paired-end pair(s)",
            [メッセージID.単純化の収束] = "[Debug] Simplification converged after {0} round(s)",
            [メッセージID.単純化の打ち切り] = "[Debug] Simplification stopped at the round limit ({0}) without converging",
            [メッセージID.バブル除去数] = "[Debug] Popped {0} simple bubble branch(es) in total (kept as standalone contigs; only graph edges were removed)",
            [メッセージID.反復解決数] = "[Debug] Repeat resolution: duplicated and untangled {0} short repeat(s) (<= {1}bp) using spanning read pairs",
            [メッセージID.辺選択の内訳] = "[Debug] Edge selection: {0} vertex(es) with a single out-edge, {1} branch(es) resolved by read support, {2} branch(es) unresolved due to multi-copy repeats (reads inside repeats cannot distinguish copies)",
            [メッセージID.反復通り抜けで棄却した結合数] = "[Debug] Rejected {0} join(s) that would traverse unresolved multi-copy repeats (traversing skips intervening sequence between repeat copies)",
            [メッセージID.相互一意で残った結合数] = "[Debug] {0} directed merge(s) survived mutual uniqueness check ({1} undirected join(s))",
            [メッセージID.環状コンティグあり] = "[Info] {0} contig(s) closed into a circle ({1}) -- indicates fully assembled replicon (chromosome or plasmid)",
            [メッセージID.環状コンティグなし] = "[Info] No circular contigs found; all replicons remain fragmented",
            [メッセージID.確定辺標本数] = "[Info] Insert size samples derived from resolved unitig adjacencies: {0}",
            [メッセージID.確定辺標本の中央値] = "[Info] Resolved-edge sample median: {0} (from {1} samples; unaffected by same-unitig length bias)",
            [メッセージID.短すぎるユニティグの除外] = "[Warning] Skipped {0} unitig(s) shorter than k-mer length during mapping",
            [メッセージID.曖昧なkmer登録] = "[Warning] Ignored {0} ambiguous k-mer registration(s) (shared across multiple unitigs) during mapping",
            [メッセージID.ペア隣接候補数] = "[Info] Paired-end adjacency candidates: {0} edges ({1} supporting pairs total)",
            [メッセージID.同一ユニティグのペア向き集計] = "[Info] Same-unitig pair orientation counts: same={0}, opposite={1} -- using '{2}' as observed library orientation for insert size estimation ({3} samples)",
            [メッセージID.同一ユニティグの断片長分布] = "[Info] Same-unitig fragment size distribution: {0}",
            [メッセージID.同一ユニティグの断片長中央値] = "[Info] Same-unitig fragment size median: {0} (from {1} samples; true fragment size including read lengths; may be underestimated if unitigs are shorter than true insert size)",
            [メッセージID.ペアリードIDの不一致] = "[Warning] Paired read ID mismatch at this position (\"{0}\" vs \"{1}\") -- paired-end adjacency detection may be unreliable beyond this point (single-read detection unaffected)",
            [メッセージID.統合できる接合点なし] = "[Merge] No backbone junction was spanned by other k values; keeping original assembly",
            [メッセージID.統合した接合点数] = "[Merge] Joined {0} backbone junction(s) using sequences from other k values",
            [メッセージID.候補一覧の見出し] = "[Multi-k] Candidate assemblies (reference-free evaluation against common anchor k-mer set):",
            [メッセージID.候補一覧の明細] = "[Multi-k]   k={0,3}: {1}{2}",
            [メッセージID.統計_ファイルなし] = "[Stats] {0}: (file not found: {1})",
            [メッセージID.統計] = "[Stats] {0}: {1}",
            [メッセージID.統計_長さで絞り込み] = "[Stats] {0} (>={1}bp, comparable to abyss-fac): {2}",
            [メッセージID.検査_対象外のk長] = "[Check] {0}: skipped (self-check supports k <= 64 only)",
            [メッセージID.検査_取りこぼし] = "[Check] {0}: {1:N0} trusted k-mer(s); {2:N0} ({3:0.00}%) missing from assembly (trimmed or unreached sequence)",
            [メッセージID.検査_出しすぎ] = "[Check] {0}: {1:N0} k-mer instance(s) in assembly; {2:N0} ({3:0.00}%) exceed coverage-supported copy count across {4:N0} distinct k-mer(s) -- inflated assembly length",
            [メッセージID.kmerインデックス構築開始] = "Building k-mer index",
            [メッセージID.kmerカットオフ適用] = "Applying k-mer cutoff",
            [メッセージID.引き継ぎで追加したkmer数] = "[Carry-over] Added {0:N0} k-mer(s) from previous k that were unobserved at current k",
            [メッセージID.tip除去開始] = "Clipping short tips",
            [メッセージID.ユニティグ構築開始] = "Constructing unitigs",
            [メッセージID.グラフが複雑すぎる] = "[Warning] Assembly graph too complex at k={0} (unitig count exceeded {1}); skipping this k",
            [メッセージID.リードのマッピング開始] = "Mapping reads to unitigs",
            [メッセージID.ユニティグ結合開始] = "Merging unitigs",
            [メッセージID.rMer検証の見送り] = "[Info] Skipped repeat r-mer verification for k={0}: required r-mer length ({1}bp) exceeds 32bp packing limit",
            [メッセージID.コンティグ構築完了] = "Contig assembly complete",
            [メッセージID.スキャフォールディング開始] = "Scaffolding contigs",
            [メッセージID.ギャップ充填開始] = "Filling scaffold gaps",
            [メッセージID.kが薄すぎて省略] = "[Multi-k] Skipping k={0}: predicted k-mer coverage {1:F1}x is below threshold {2:F1}x (insufficient for usable graph)",
            [メッセージID.kの開始見出し] = "[Multi-k] ===== Assembling with k={0} =====",
            [メッセージID.kでアセンブリできず] = "[Multi-k] k={0} produced no assembly; skipping",
            [メッセージID.単一のkのみ成功] = "[Multi-k] Only one k produced an assembly; selected without comparison",
            [メッセージID.アンカーkmer集合の構築] = "[Multi-k] Building common anchor k-mer set (k={0}) for comparison",
            [メッセージID.アンカースペクトルが二峰でない] = "[Multi-k] Anchor k-mer spectrum is not bimodal; candidates cannot be compared",
            [メッセージID.候補を評価できない] = "[Multi-k] Could not evaluate candidates; falling back to largest k",
            [メッセージID.採用したk] = "[Multi-k] Selected k={0}",
            [メッセージID.統合開始] = "[Merge] Merging sequences from other k values into selected assembly",
            [メッセージID.統合結果を評価できない] = "[Merge] Could not evaluate merged assembly; keeping selected assembly",
            [メッセージID.統合前の評価] = "[Merge]   Before: {0}",
            [メッセージID.統合後の評価] = "[Merge]   Merged: {0}",
            [メッセージID.統合が骨格に勝てず] = "[Merge] Merged assembly did not improve upon selected assembly; keeping selected assembly",
            [メッセージID.統合結果を採用] = "[Merge] Using merged assembly",
            [メッセージID.エラー訂正_スペクトル構築] = "[ErrorCorrection] Building k-mer spectrum...",
            [メッセージID.エラー訂正_訂正開始] = "[ErrorCorrection] Correcting reads...",
            [メッセージID.エラー訂正_ファイル別統計] = "[ErrorCorrection] {0}: corrected {1}/{2} reads ({3} base corrections total)",
            [メッセージID.リード読込完了] = "Loaded {0} reads from {1}",
            [メッセージID.リード2の読込開始] = "Loading reverse reads file",
            [メッセージID.前処理統計] = "[Preprocess] {0}/{1} pair(s) exhibited adapter read-through (trimmed to overlap length); {2} base(s) mutually corrected",
            [メッセージID.SuperRead統計] = "[SuperRead] {0}/{1} pair(s) bridged into synthetic reads and carried over to next k",
            [メッセージID.SuperRead統計_重なり] = "[SuperRead] Bridged pairs: {0} joined by direct mate overlap, {1} by graph path",
            [メッセージID.SuperRead統計_曖昧] = "[SuperRead] Deferred {0} pair(s) with ambiguous overlaps to graph search (repeats matched multiple positions)",
            [メッセージID.短い配列を除外] = "[Info] Removed {0} sequence(s) shorter than {1}bp ({2}bp total) from final output (preserved in working directory)",
            [メッセージID.最終成果物] = "[Info] Final assembly: {0} (unitigs, contigs, and scaffolds represent intermediate stages before merging, filtering, and polishing)",
            [メッセージID.ギャップ充填_対象なし] = "[Info] Gap filling: no gaps to fill",
            [メッセージID.ギャップ充填統計] = "[Info] Gap filling: closed {0}/{1} gap(s) with sequence ({2:N0}bp of N replaced); {3} retained as N due to multiple paths, {4} due to no connecting path",
            [メッセージID.局所アセンブリ_対象なし] = "[Info] Local assembly: no eligible remaining gaps",
            [メッセージID.局所アセンブリ統計] = "[Info] Local assembly: closed {0}/{1} gap(s) via local re-assembly ({2:N0}bp of N replaced); {3} lacked local reads, {4} had multiple local paths, {5} had no connecting path",
            [メッセージID.スキャフォールディング省略_インサートサイズ不明] = "[Info] Scaffolding skipped: insert size was unspecified and could not be estimated from mapped pairs",
            [メッセージID.スキャフォールディング開始_インサートサイズ] = "[Info] Scaffolding with insert size = {0}",
            [メッセージID.スキャフォールディング省略_コンティグなし] = "[Info] Scaffolding skipped: no contigs found",
            [メッセージID.内部を指したペア候補] = "[Info] Skipped {0} paired-end candidate(s) pointing to unitigs inside already-joined contigs",
            [メッセージID.未配置を指したペア候補] = "[Info] Skipped {0} paired-end candidate(s) referencing unplaced unitigs (e.g. too short)",
            [メッセージID.閾値後のスキャフォールド辺] = "[Info] Scaffold edges resolved after thresholding: {0} ({1} rejected by mutual uniqueness check, {2} retained)",
            [メッセージID.スキャフォールド出力完了] = "[Info] Wrote {0} scaffold(s) (total length {1}) to {2}",
            [メッセージID.インサートサイズ推定_同一ユニティグ] = "[Info] Insert size estimated as {0} from {1} same-unitig pair samples (median; unitig N50 {2} >= {3}x estimate, truncation bias inapplicable)",
            [メッセージID.インサートサイズ推定_確定辺] = "[Info] Insert size estimated as {0} from {1} resolved-edge pair samples (median; preferred over same-unitig samples due to length constraints)",
            [メッセージID.インサートサイズ推定_標本不足] = "[Info] Insert size auto-estimation requires at least {0} samples (collected {1} resolved-edge and {2} total samples)",
            [メッセージID.インサートサイズ推定_全標本] = "[Info] Insert size estimated as {0} from {1} total pair samples (median; fell back to full pool due to insufficient resolved-edge samples ({2}), may be underestimated)",
            [メッセージID.単一コピー基準値] = "[Info] Single-copy coverage baseline estimated at {0:0.#} (length-weighted median)",
            [メッセージID.コピー数の要約] = "[Info] Estimated copy numbers: {0}",
            [メッセージID.反復配列の割合] = "[Info] Multi-copy repeat content: {0:N0}bp / {1:N0}bp ({2:0.0}% of assembly is repetitive)",
            [メッセージID.グラフ単純化の反復] = "[GraphSimplifier] Iteration {0}: evaluated {1} unitig(s) (tip threshold < {2}bp, baseline coverage {3:0.#}); removed {4} tip(s), trimmed {5} low-coverage k-mer(s) from {6} edge(s)",
            [メッセージID.rMer検証による棄却] = "[Debug] r-mer verification vetoed {0} repeat duplication(s) unconfirmed by junction-spanning reads",
            [メッセージID.例外を無視_見出し] = "[Warning] The following exception will be ignored:",
            [メッセージID.例外を無視_メソッド] = "          Method: {0}",
            [メッセージID.停止_見出し] = "[Error] Execution stopped:",
            [メッセージID.停止_メソッド] = "        Method: {0}",
            [メッセージID.タイムスタンプ] = "[Log] {0:yyyy/MM/dd HH:mm:ss}",
            [メッセージID.Phred_明示指定と不一致] = "[Warning] Quality scores appear to be Phred{0}, but -p {1} was specified; honoring explicit setting (re-run with -p {2} if data is indeed Phred{3})",
            [メッセージID.Phred_自動判定] = "[Info] Auto-detected Phred offset as {0} from quality scores (observed ASCII range [{1}, {2}]); pass -p to override",
            [メッセージID.Phred_検査の警告] = "[Warning] Phred encoding check for {0}: {1}",
            [メッセージID.kmerカットオフ_混合モデル] = "[Info] Auto-selected k-mer cutoff as {0} via 2-component mixture model (single-copy mean {1:0.#}, trust limit {2}, {3} EM iterations); pass -kc to override",
            [メッセージID.kmerカットオフ_谷が不明] = "[Info] Could not identify distinct histogram valley; keeping -kc {0}",
            [メッセージID.kmerカットオフ_スペクトル] = "[Info] Auto-selected k-mer cutoff as {0} from k-mer spectrum; pass -kc to override",
            [メッセージID.kmerヒストグラム] = "[Info] k-mer count histogram (count: distinct kmers): {0}",
            [メッセージID.スペクトルの谷が不明] = "[Info] Could not identify distinct histogram valley (spectrum may lack bimodal distribution)",
            [メッセージID.スペクトルの谷とピーク] = "[Info] k-mer spectrum: valley at count {0} ({1} distinct kmers), single-copy peak at count {2} ({3} distinct kmers)",
            [メッセージID.ゲノムサイズとカバレッジの推定] = "[Info] Estimated genome size: {0:N0} bp, estimated coverage: {1}",
            [メッセージID.k自動選択_リード長不明] = "[Info] Could not sample read length; keeping -k {0}",
            [メッセージID.k自動選択_kが長すぎる] = "[Warning] Specified -k {0} is not shorter than observed read length ({1} bp); lower -k value",
            [メッセージID.k自動選択_リード長が短い] = "[Info] Observed read length ({0} bp) is too short for automatic k selection; keeping -k {1}",
            [メッセージID.k自動選択] = "[Info] Auto-selected k={0} based on observed read length ({1} bp); pass -k to override",
            [メッセージID.開始kmerの探索] = "[Debug] Searching for initial k-mer",
            [メッセージID.一時ディレクトリを残した] = "[Info] Output and intermediate files retained in {0} (use {1} to delete intermediates)",
            [メッセージID.中間ファイルを削除した] = "[Info] Deleted intermediate files in {0}; final output and log retained",
            [メッセージID.支持検査の開始] = "[Check] Verifying read support for every {0}-mer in final assembly",
            [メッセージID.支持検査の結果] = "[Check] Read support ({0}-mer): {1} / {2} positions ({3}%) unobserved in reads across {4} stretch(es)",
            [メッセージID.支持のない箇所を書き出した] = "[Check] Wrote {0} unsupported stretch(es) to {1}",
            [メッセージID.検査項目_リードの支持] = "read support",
            [メッセージID.リード長の観測値] = "[Info] Observed read length (sampled median): {0} bp",
            [メッセージID.一時ディレクトリが既にある] = "Directory {0} already exists",
            [メッセージID.パスの確認] = "Please verify specified path",
            [メッセージID.前処理省略_ペアなし] = "[Warning] -pp requires paired-end input (read2 unspecified); skipping preprocessing",
            [メッセージID.前処理開始] = "Preprocessing reads (adapter trimming and error correction)",
            [メッセージID.エラー訂正開始] = "Correcting read errors prior to assembly",
            [メッセージID.開発中] = "Under development",
            [メッセージID.コンティグ総延長] = "Total contig length: {0}",
            [メッセージID.リードファイルのパス] = "{0}",
            [メッセージID.試すk一覧] = "[Multi-k] Testing k = {0}",
            [メッセージID.リード読込の進捗] = "[Debug] Loaded {0} reads",
            [メッセージID.リード1の読込開始] = "Loading forward reads file",
            [メッセージID.単一リードの読込開始] = "Loading reads file",
            [メッセージID.スキャフォールド候補辺数] = "[Info] Candidate scaffold edges (contig-level, pre-threshold): {0}{1}",
            [メッセージID.理想本数モデルあり] = " (ideal-count model available)",
            [メッセージID.理想本数モデルなし] = " (ideal-count model unavailable)",
            [メッセージID.Phred_ファイル間で不一致] = "[Warning] Discrepancy in Phred offset inference between read files (read1 -> {0}, read2 -> {1}); retaining -p {2}",
            [メッセージID.Phred_未確定] = "undetermined",
            [メッセージID.kmer種類数] = "[Debug] Distinct k-mers: {0}",
            [メッセージID.採用kmer数] = "[Debug] Retained k-mers: {0}",
            [メッセージID.アセンブリ不能] = "\nGenome complexity too high to assemble with current settings\nPlease adjust parameters\n",
            [メッセージID.概要_説明] = "Tsumiki is a genome assembler",
            [メッセージID.概要_バージョン] = "Version: {0}",
            [メッセージID.ヘルプ_使い方] = "Usage: tsumiki {0} <path> [{1} <path>] [options]",
            [メッセージID.ヘルプ節_入力] = "# Input",
            [メッセージID.ヘルプ節_kmerと品質] = "# k-mer / Quality",
            [メッセージID.ヘルプ節_ペアエンド] = "# Paired-end / Scaffolding",
            [メッセージID.ヘルプ節_前処理] = "# Preprocessing",
            [メッセージID.ヘルプ節_マルチk] = "# Multi-k Assembly",
            [メッセージID.ヘルプ節_反復の安全策] = "# Repeat Resolution Safeguards",
            [メッセージID.ヘルプ節_出力とその他] = "# Output / Misc",
            [メッセージID.ヘルプ_リード1] = "Forward fastq(.gz) path (required; also used for single-end reads)",
            [メッセージID.ヘルプ_リード2] = "Reverse fastq(.gz) path",
            [メッセージID.ヘルプ_曖昧塩基] = "Allow ambiguous bases (e.g. N) in reads (default: false)",
            [メッセージID.ヘルプ_k長] = "k-mer length; comma-separated list (e.g. 31,63,95) tests each value and retains the best result, equivalent to {0} (default: auto-selected from read length, capped at {1})",
            [メッセージID.ヘルプ_kmerカットオフ] = "Minimum trusted k-mer count (default: auto-selected from k-mer spectrum)",
            [メッセージID.ヘルプ_Phred] = "Phred score ASCII offset ({0}) (default: {1})",
            [メッセージID.ヘルプ_クオリティカットオフ] = "Minimum trusted base quality score (default: {0})",
            [メッセージID.ヘルプ_メモリ予算] = "Memory limit for k-mer counting, e.g. 2G, 512M (default: {0})",
            [メッセージID.ヘルプ_インサートサイズ] = "Expected insert size (default: auto-estimated from mapped pairs)",
            [メッセージID.ヘルプ_ペア結合閾値] = "Minimum dominance ratio required to accept scaffold edges (default: {0})",
            [メッセージID.ヘルプ_ペア支持数閾値] = "Minimum read-pair support required to resolve short repeats (default: {0})",
            [メッセージID.ヘルプ_積極性モード] = "Preset for {0}/{1} balancing completeness and accuracy (default: {2})",
            [メッセージID.ヘルプ_前処理] = "Trim adapter read-through and cross-correct low-quality bases using mate overlaps (default: false)",
            [メッセージID.ヘルプ_エラー訂正] = "Correct read errors based on k-mer spectrum prior to assembly (default: false)",
            [メッセージID.ヘルプ_マルチk] = "Assemble across multiple k values and select the best (default: false; up to {0}x runtime)",
            [メッセージID.ヘルプ_引き継ぎなし] = "Do not carry over sequences between k iterations (default: false)",
            [メッセージID.ヘルプ_SuperRead] = "Bridge paired-end reads into synthetic long reads for carry-over (default: false)",
            [メッセージID.ヘルプ_マージ] = "Splice sequences from other k values into unresolved backbone junctions (default: false; may increase misassemblies)",
            [メッセージID.ヘルプ_反復rMer検証] = "Require raw-read r-mer support before duplicating short repeats (default: false)",
            [メッセージID.ヘルプ_局所アセンブリ] = "Reassemble unresolved scaffold gaps using reads mapped to gap flanks; safer than {0} (default: false)",
            [メッセージID.ヘルプ_GFA出力] = "Export unitig graph in GFA1 format ({0}) for visualization tools like Bandage (default: false)",
            [メッセージID.ヘルプ_一時ディレクトリ] = "Working directory for final output, per-k assemblies, and intermediate files (default: {0})",
            [メッセージID.ヘルプ_一時ディレクトリ削除] = "Delete intermediate files upon completion, keeping final output and logs (default: false)",
            [メッセージID.ヘルプ_スレッド数] = "Worker threads for read loading (default: logical processor count)",
            [メッセージID.ヘルプ_言語] = "Message language (default: {0})",
            [メッセージID.ヘルプ_バージョン] = "Display version information and exit",
            [メッセージID.ヘルプ_ヘルプ] = "Display usage information and exit",
            [メッセージID.引き継ぎの統合開始] = "Merging {0:N0} carry-over sequence(s) from previous k",
            [メッセージID.引き継ぎの統合進捗] = "[Carry-over] Merged {0:N0} / {1:N0} sequence(s)",
            [メッセージID.引き継ぎの準備開始] = "Preparing carry-over sequences for next k",
            [メッセージID.引き継ぎの準備完了] = "[Carry-over] Prepared {0:N0} sequence(s) for next k",
            [メッセージID.SuperRead橋渡し開始] = "[SuperRead] Bridging read pairs",
            [メッセージID.SuperRead橋渡し進捗] = "[SuperRead] Processed {0:N0} pair(s), bridged {1:N0}",
            [メッセージID.ポリッシュ開始] = "[Polish] Remapping reads onto final assembly",
            [メッセージID.ポリッシュの索引構築] = "[Polish] Indexing {0:N0} sequence(s) ({1:N0} bp total)",
            [メッセージID.ポリッシュの種が無い] = "[Polish] No valid {0}-mer seed extracted; skipping polishing",
            [メッセージID.ポリッシュのマッピング開始] = "[Polish] Mapping reads",
            [メッセージID.ポリッシュの深度中央値] = "[Polish] Median depth: {0:F1}x",
            [メッセージID.ポリッシュを行えず] = "[Polish] No sequences available for polishing",
            [メッセージID.ポリッシュのマッピング結果] = "[Polish] Placed {0:N0} read(s), rejected {1:N0}",
            [メッセージID.ポリッシュの訂正結果] = "[Polish] Corrected {0:N0} / {1:N0} base(s)",
            [メッセージID.ポリッシュの深度不足] = "[Polish] Low-depth positions: {0:N0} / {1:N0} ({2:F2}%)",
            [メッセージID.閉じ目の検証開始] = "[Closure] Verifying read coverage across circular junctions ({0} sequences, {1}bp window)",
            [メッセージID.閉じ目_環状の配列が無い] = "[Closure] No circular sequences found in assembly",
            [メッセージID.閉じ目を裏付けた] = "[Closure] {0} ({1:N0} bp): verified with {2} junction-spanning read(s) (required: {3})",
            [メッセージID.閉じ目を裏付けられず] = "[Closure] {0} ({1:N0} bp): insufficient read support ({2} spanning read(s), required: {3})",
            [メッセージID.検査項目_グラフ被覆] = "graph coverage",
            [メッセージID.検査項目_コピー数整合] = "copy number consistency",
            [メッセージID.検査項目_深度の連続性] = "coverage continuity",
            [メッセージID.検査項目_未解決のギャップ] = "unresolved gaps",
            [メッセージID.検査項目_接合点の支持] = "junction support",
            [メッセージID.検査項目_競合経路] = "competing paths",
            [メッセージID.検査項目_環状閉鎖] = "circular closure",
            [メッセージID.検査判定_合格] = "PASS",
            [メッセージID.検査判定_不合格] = "FAIL",
            [メッセージID.検査判定_判定不能] = "UNKNOWN",
            [メッセージID.完全性の見出し] = "[Complete] Completeness validation:",
            [メッセージID.完全性の検査行] = "[Complete]   {0}: {1} {2}",
            [メッセージID.完全長と判定] = "[Complete] Complete (Q{0})",
            [メッセージID.完全長に届かず] = "[Complete] Incomplete (Q{0})",
            [メッセージID.完全性の未達理由] = "[Complete] Reasons: {0}",
            [メッセージID.救済kmerの開始] = "[Mercy] Rescuing sub-cutoff k-mers flanked by trusted k-mers within reads",
            [メッセージID.救済_対象外のk長] = "[Mercy] k={0} exceeds 64; rescue algorithm unavailable",
            [メッセージID.救済したkmer数] = "[Mercy] Rescued {0:N0} / {1:N0} candidate k-mer(s)",
            [メッセージID.レポートを書き出した] = "[Report] Generated {0}",
            [メッセージID.曖昧箇所を書き出した] = "[Report] Wrote {0:N0} ambiguous site(s) to {1}",
            [メッセージID.再開_中間ファイルを再利用] = "[Resume] Reusing {0}",
            [メッセージID.ヘルプ節_完全性の検証] = "# Completeness Validation",
            [メッセージID.ヘルプ_ポリッシュ] = "Remap reads to final assembly and correct substitution errors by majority vote (default: false)",
            [メッセージID.ヘルプ_環状閉鎖検証] = "Require junction-spanning read support before classifying sequences as circular (default: false)",
            [メッセージID.ヘルプ_救済kmer] = "Rescue sub-cutoff k-mers flanked by trusted k-mers within reads (default: false)",
            [メッセージID.ヘルプ_再開] = "Reuse preprocessed and error-corrected reads from working directory (default: false)",
            [メッセージID.ヘルプ_レポートの説明] = "{0} and {1} are generated automatically alongside assembly files",
            [メッセージID.分岐のない閉路] = "[Info] Recovered {0} unbranched closed loop(s) missed by standard entry criteria",
            [メッセージID.孤立した環状の複製単位] = "[Info] Circularized {0} self-contained replicon(s) end-to-end",
            [メッセージID.ヘルプ_ログ水準] = "Console log verbosity level (default: {0}); full log is always saved to {1} in temp directory",
            [メッセージID.ログの保存先] = "[Info] Complete execution log saved to {0}",
            [メッセージID.短すぎる閉路] = "[Debug] Ignored {0} closed loop(s) shorter than {1}bp (likely homopolymer or tandem repeat artifacts)",
            [メッセージID.合成リードを再利用] = "[SuperRead] Reusing {0:N0} synthetic read(s) constructed at initial k",
        };

        /// <summary>
        /// 日本語
        /// </summary>
        private static readonly Dictionary<メッセージID, string> _日本語 = new()
        {
            [メッセージID.デブルーイングラフの要約] = "[Debug] de Bruijn ユニティググラフ: 有向辺 {0} 本、分岐頂点 {1} 個 / 全 {2} 頂点",
            [メッセージID.先読みで解決した分岐数] = "[Debug] ビーム探索の先読みにより、相互一意判定で未確定の分岐をさらに {0} 箇所解決",
            [メッセージID.GFA出力完了] = "[Info] ユニティググラフを出力: {0} (GFA1)",
            [メッセージID.分岐選択の重み内訳] = "[Debug] 分岐選択の重み: 単一リード由来隣接 {0} 件 + ペアエンド由来 {1} 件",
            [メッセージID.単純化の収束] = "[Debug] グラフ単純化が {0} ラウンドで収束",
            [メッセージID.単純化の打ち切り] = "[Debug] グラフ単純化が上限ラウンド ({0}) に達したため打ち切り",
            [メッセージID.バブル除去数] = "[Debug] 単純バブル枝を {0} 本除去 (配列自体はコンティグとして保持しグラフ辺のみ削除)",
            [メッセージID.反復解決数] = "[Debug] 反復解決: 短い反復 (<= {1}bp) {0} 箇所をまたぐリードペアにより複製・分離",
            [メッセージID.辺選択の内訳] = "[Debug] 辺の選択: 単一出辺頂点 {0} 個、リード支持解決 {1} 個、多コピー反復由来の未解決 {2} 個 (反復内のリードではコピーを識別不可)",
            [メッセージID.反復通り抜けで棄却した結合数] = "[Debug] 未分離の多コピー反復を経由する結合 {0} 件を棄却 (挟まれた配列の脱落を防止)",
            [メッセージID.相互一意で残った結合数] = "[Debug] 相互一意検査を通過した有向マージ: {0} 件 (無向換算: {1} 件)",
            [メッセージID.環状コンティグあり] = "[Info] 環状コンティグ: {0} 本 ({1}) -- 染色体またはプラスミドが完全長で構築完了",
            [メッセージID.環状コンティグなし] = "[Info] 環状コンティグなし (全レプリコンが断片化状態)",
            [メッセージID.確定辺標本数] = "[Info] 確定ユニティグ隣接由来のインサートサイズ標本数: {0}",
            [メッセージID.確定辺標本の中央値] = "[Info] 確定辺標本の中央値: {0} (標本数: {1}、同一ユニティグ標本由来の長尺バイアスなし)",
            [メッセージID.短すぎるユニティグの除外] = "[Warning] k-mer 長未満のユニティグ {0} 本をマッピング対象から除外",
            [メッセージID.曖昧なkmer登録] = "[Warning] 複数ユニティグで共有される曖昧な k-mer 登録 {0} 件をマッピング時に無視",
            [メッセージID.ペア隣接候補数] = "[Info] ペアエンド隣接候補: {0} 辺 (支持リードペア延べ {1} 組)",
            [メッセージID.同一ユニティグのペア向き集計] = "[Info] 同一ユニティグ内ペアの向き: 同方向 {0} 件、逆方向 {1} 件 -- ライブラリ向きとして '{2}' を採用 (標本数: {3})",
            [メッセージID.同一ユニティグの断片長分布] = "[Info] 同一ユニティグ内の断片長分布: {0}",
            [メッセージID.同一ユニティグの断片長中央値] = "[Info] 同一ユニティグ内の断片長中央値: {0} (標本数: {1}、リード長算入済みの真の断片長。ユニティグが短ければ下振れ可能性あり)",
            [メッセージID.ペアリードIDの不一致] = "[Warning] ペアリード ID の不一致を検出 (\"{0}\" vs \"{1}\") -- 以降のペアエンド隣接検出の信頼性が低下する可能性あり (単一リード検出は影響なし)",
            [メッセージID.統合できる接合点なし] = "[Merge] 他の k で架橋できる骨格接合点なし (現行アセンブリを維持)",
            [メッセージID.統合した接合点数] = "[Merge] 他の k の配列を用いて骨格接合点 {0} 箇所を連結",
            [メッセージID.候補一覧の見出し] = "[Multi-k] 候補アセンブリ (共通アンカー k-mer 集合による評価):",
            [メッセージID.候補一覧の明細] = "[Multi-k]   k={0,3}: {1}{2}",
            [メッセージID.統計_ファイルなし] = "[Stats] {0}: (ファイル未検出: {1})",
            [メッセージID.統計] = "[Stats] {0}: {1}",
            [メッセージID.統計_長さで絞り込み] = "[Stats] {0} (>={1}bp、abyss-fac 比較条件): {2}",
            [メッセージID.検査_対象外のk長] = "[Check] {0}: スキップ (自己検査機能は k <= 64 のみ対応)",
            [メッセージID.検査_取りこぼし] = "[Check] {0}: 信頼 k-mer {1:N0} 個中 {2:N0} 個 ({3:0.00}%) がアセンブリ未反映 (トリミング済または未到達の配列)",
            [メッセージID.検査_出しすぎ] = "[Check] {0}: アセンブリ内 k-mer 総数 {1:N0} 個中 {2:N0} 個 ({3:0.00}%) がカバレッジ超過 ({4:N0} 種類、配列長の過大評価部分)",
            [メッセージID.kmerインデックス構築開始] = "k-mer インデックスの構築を開始",
            [メッセージID.kmerカットオフ適用] = "k-mer カットオフを適用中",
            [メッセージID.引き継ぎで追加したkmer数] = "[Carry-over] 前の k から未観測 k-mer {0:N0} 個を補完",
            [メッセージID.tip除去開始] = "短い tip を除去中",
            [メッセージID.ユニティグ構築開始] = "ユニティグの構築を開始",
            [メッセージID.グラフが複雑すぎる] = "[Warning] k={0} でのグラフ構造が複雑すぎます (ユニティグ数が上限 {1} を超過) -- この k をスキップ",
            [メッセージID.リードのマッピング開始] = "リードのユニティグマッピングを開始",
            [メッセージID.ユニティグ結合開始] = "ユニティグの結合を開始",
            [メッセージID.rMer検証の見送り] = "[Info] k={0} での反復 r-mer 検証をスキップ (r-mer 長 {1}bp が 32bp パック上限を超過)",
            [メッセージID.コンティグ構築完了] = "コンティグ構築が完了",
            [メッセージID.スキャフォールディング開始] = "コンティグのスキャフォールディングを開始",
            [メッセージID.ギャップ充填開始] = "スキャフォールドのギャップ充填を開始",
            [メッセージID.kが薄すぎて省略] = "[Multi-k] k={0} をスキップ (予測 k-mer カバレッジ {1:F1}x が閾値 {2:F1}x 未満のためグラフ構築不可)",
            [メッセージID.kの開始見出し] = "[Multi-k] ===== k={0} アセンブリ開始 =====",
            [メッセージID.kでアセンブリできず] = "[Multi-k] k={0} でのアセンブリ生成に失敗 -- この k をスキップ",
            [メッセージID.単一のkのみ成功] = "[Multi-k] アセンブリ成功が 1 つの k のみのため比較なしで採用",
            [メッセージID.アンカーkmer集合の構築] = "[Multi-k] 比較用の共通アンカー k-mer 集合 (k={0}) を構築中",
            [メッセージID.アンカースペクトルが二峰でない] = "[Multi-k] アンカー k-mer スペクトルが二峰性を示さないため候補比較を中止",
            [メッセージID.候補を評価できない] = "[Multi-k] 候補評価不能のため最大 k の結果へフォールバック",
            [メッセージID.採用したk] = "[Multi-k] k={0} を選択",
            [メッセージID.統合開始] = "[Merge] 他の k の配列を選択済みアセンブリへ統合中",
            [メッセージID.統合結果を評価できない] = "[Merge] 統合結果の評価不能のため選択済みアセンブリを維持",
            [メッセージID.統合前の評価] = "[Merge]   統合前: {0}",
            [メッセージID.統合後の評価] = "[Merge]   統合後: {0}",
            [メッセージID.統合が骨格に勝てず] = "[Merge] 統合結果が選択済みアセンブリの品質を下回るため現状維持",
            [メッセージID.統合結果を採用] = "[Merge] 統合済みアセンブリを採用",
            [メッセージID.エラー訂正_スペクトル構築] = "[ErrorCorrection] k-mer スペクトルを構築中...",
            [メッセージID.エラー訂正_訂正開始] = "[ErrorCorrection] リードのエラー訂正を実行中...",
            [メッセージID.エラー訂正_ファイル別統計] = "[ErrorCorrection] {0}: リード {1}/{2} 件を訂正 (塩基訂正総数: {3})",
            [メッセージID.リード読込完了] = "{1} から {0} 件のリードを読み込み完了",
            [メッセージID.リード2の読込開始] = "リバースリードファイルを読み込み中",
            [メッセージID.前処理統計] = "[Preprocess] {1} ペア中 {0} ペアでアダプタ読み抜けを検出・トリミング (塩基相互訂正数: {2})",
            [メッセージID.SuperRead統計] = "[SuperRead] {1} ペア中 {0} ペアを 1 本の合成リードへ架橋し次の k へ引き継ぎ",
            [メッセージID.SuperRead統計_重なり] = "[SuperRead] 架橋内訳: ペア直接オーバーラップ {0} 件、グラフ経路による結合 {1} 件",
            [メッセージID.SuperRead統計_曖昧] = "[SuperRead] 重なり位置が不確定な {0} ペアをグラフ探索へ委ねました (反復配列等の複数アライメント)",
            [メッセージID.短い配列を除外] = "[Info] {1}bp 未満の配列 {0} 本 (計 {2}bp) を最終成果物から除外 (作業用ディレクトリ内には保持)",
            [メッセージID.最終成果物] = "[Info] 最終アセンブリ: {0} (unitigs/contigs/scaffolds は統合・除外・ポリッシュ前の段階的成果物)",
            [メッセージID.ギャップ充填_対象なし] = "[Info] ギャップ充填: 対象となるギャップなし",
            [メッセージID.ギャップ充填統計] = "[Info] ギャップ充填: {1} 箇所中 {0} 箇所を実配列で充填 ({2:N0}bp の N を置換) / 複数経路 {3} 箇所、非連結 {4} 箇所を N として保持",
            [メッセージID.局所アセンブリ_対象なし] = "[Info] 局所アセンブリ: 対象となる残りギャップなし",
            [メッセージID.局所アセンブリ統計] = "[Info] 局所アセンブリ: 残り {1} 箇所中 {0} 箇所を局所再構築リードで充填 ({2:N0}bp の N を置換) / リード不備 {3}、複数経路 {4}、非連結 {5}",
            [メッセージID.スキャフォールディング省略_インサートサイズ不明] = "[Info] スキャフォールディングをスキップ (インサートサイズ未指定かつマップドペアから推定不可)",
            [メッセージID.スキャフォールディング開始_インサートサイズ] = "[Info] インサートサイズ {0} でスキャフォールディングを開始",
            [メッセージID.スキャフォールディング省略_コンティグなし] = "[Info] スキャフォールディングをスキップ (コンティグ未検出)",
            [メッセージID.内部を指したペア候補] = "[Info] 結合済みコンティグ内部を指すペアエンド候補 {0} 件をスキップ (端点はコンティグ構築時に解決済み)",
            [メッセージID.未配置を指したペア候補] = "[Info] コンティグ未配置のユニティグを指すペアエンド候補 {0} 件をスキップ",
            [メッセージID.閾値後のスキャフォールド辺] = "[Info] 閾値処理後に確定したスキャフォールド辺: {0} 本 (相互一意検査棄却: {1} 本、採用: {2} 本)",
            [メッセージID.スキャフォールド出力完了] = "[Info] スキャフォールド {0} 本 (総延長 {1}) を {2} へ出力完了",
            [メッセージID.インサートサイズ推定_同一ユニティグ] = "[Info] 同一ユニティグ標本 {1} 件からインサートサイズを {0} と推定 (中央値、ユニティグ N50 {2} >= 推定値の {3} 倍のため短尺バイアスなし)",
            [メッセージID.インサートサイズ推定_確定辺] = "[Info] 確定辺標本 {1} 件からインサートサイズを {0} と推定 (中央値、同一ユニティグ標本の長尺偏りを回避するため優先採用)",
            [メッセージID.インサートサイズ推定_標本不足] = "[Info] インサートサイズ自動推定に必要な標本数不足 (必要: {0} 件、確定辺: {1} 件、全体: {2} 件)",
            [メッセージID.インサートサイズ推定_全標本] = "[Info] 全標本 {1} 件からインサートサイズを {0} と推定 (中央値、確定辺標本不足 ({2} 件) のため全プールへフォールバック。下振れ可能性あり)",
            [メッセージID.単一コピー基準値] = "[Info] 単一コピーカバレッジ基準値の推定: {0:0.#} (長尺加重中央値)",
            [メッセージID.コピー数の要約] = "[Info] 推定コピー数: {0}",
            [メッセージID.反復配列の割合] = "[Info] 多コピー (反復) 領域の割合: {0:N0}bp / {1:N0}bp (全体の {2:0.0}%)",
            [メッセージID.グラフ単純化の反復] = "[GraphSimplifier] イテレーション {0}: ユニティグ {1} 本を評価 (tip 閾値 < {2}bp、基準カバレッジ {3:0.#}) -- tip {4} 本を除去、{6} 本の端から低カバレッジ k-mer {5} 個を修剪",
            [メッセージID.rMer検証による棄却] = "[Debug] r-mer 検証により、跨ぎリードの裏付けがない反復複製 {0} 件を否決",
            [メッセージID.例外を無視_見出し] = "[Warning] 以下の例外を無視して処理を続行します:",
            [メッセージID.例外を無視_メソッド] = "          メソッド: {0}",
            [メッセージID.停止_見出し] = "[Error] 処理が停止しました:",
            [メッセージID.停止_メソッド] = "        メソッド: {0}",
            [メッセージID.タイムスタンプ] = "[Log] {0:yyyy/MM/dd HH:mm:ss}",
            [メッセージID.Phred_明示指定と不一致] = "[Warning] クオリティ形式が Phred{0} に見えますが -p {1} が指定されています。明示指定を優先しますが、データが実際に Phred{3} の場合は -p {2} で再実行してください",
            [メッセージID.Phred_自動判定] = "[Info] Phred オフセットを {0} と自動判定 (検出 ASCII 範囲: [{1}, {2}]) -- 上書きする場合は -p を指定してください",
            [メッセージID.Phred_検査の警告] = "[Warning] {0} の Phred エンコーディング検査警告: {1}",
            [メッセージID.kmerカットオフ_混合モデル] = "[Info] 2 成分混合モデルより k-mer カットオフを {0} に自動決定 (単一コピー平均: {1:0.#}、信頼下限: {2}、EM 反復: {3} 回) -- 上書きする場合は -kc を指定してください",
            [メッセージID.kmerカットオフ_谷が不明] = "[Info] ヒストグラムの明確な谷を検出不可 (二峰性スペクトルの欠如) -- -kc {0} を保持",
            [メッセージID.kmerカットオフ_スペクトル] = "[Info] k-mer スペクトルより k-mer カットオフを {0} に自動決定 -- 上書きする場合は -kc を指定してください",
            [メッセージID.kmerヒストグラム] = "[Info] k-mer 出現頻度ヒストグラム (出現回数: 固有 k-mer 数): {0}",
            [メッセージID.スペクトルの谷が不明] = "[Info] ヒストグラムの明確な谷を検出できませんでした (現在のカバレッジでは二峰性を示さない可能性があります)",
            [メッセージID.スペクトルの谷とピーク] = "[Info] k-mer スペクトル: 谷 = 頻度 {0} ({1} 種類)、単一コピーピーク = 頻度 {2} ({3} 種類)",
            [メッセージID.ゲノムサイズとカバレッジの推定] = "[Info] 推定ゲノムサイズ: {0:N0} bp、推定カバレッジ: {1}",
            [メッセージID.k自動選択_リード長不明] = "[Info] リード長をサンプル抽出できなかったため -k {0} を保持",
            [メッセージID.k自動選択_kが長すぎる] = "[Warning] 指定された -k {0} が観測リード長 ({1} bp) 以上のため k-mer を抽出できません -- より小さな -k を指定してください",
            [メッセージID.k自動選択_リード長が短い] = "[Info] 観測リード長 ({0} bp) が自動選択には短すぎるため -k {1} を保持",
            [メッセージID.k自動選択] = "[Info] 観測リード長 ({1} bp) に基づき k={0} を自動選択 -- 上書きする場合は -k を指定してください",
            [メッセージID.開始kmerの探索] = "[Debug] 開始 k-mer を探索中",
            [メッセージID.一時ディレクトリを残した] = "[Info] 成果物および中間ファイルを {0} に保持 ({1} 指定で中間ファイルを削除可能)",
            [メッセージID.中間ファイルを削除した] = "[Info] {0} 内の中間ファイルを削除完了 (最終成果物およびログは保持)",
            [メッセージID.支持検査の開始] = "[Check] 最終アセンブリの全 {0}-mer に対するリード支持を検証中",
            [メッセージID.支持検査の結果] = "[Check] リード支持率 ({0}-mer): 全 {2} 位置中 {1} 位置 ({3}%) がリード未検出 (非支持区間: {4} 箇所)",
            [メッセージID.支持のない箇所を書き出した] = "[Check] 支持なし区間 {0} 箇所を {1} に出力完了",
            [メッセージID.検査項目_リードの支持] = "リード支持率",
            [メッセージID.リード長の観測値] = "[Info] 観測リード長 (サンプル中央値): {0} bp",
            [メッセージID.一時ディレクトリが既にある] = "ディレクトリ {0} は既に存在します",
            [メッセージID.パスの確認] = "指定されたパスを確認してください",
            [メッセージID.前処理省略_ペアなし] = "[Warning] -pp オプションにはペアエンドリードが必要です (read2 未指定) -- 前処理をスキップ",
            [メッセージID.前処理開始] = "リードの前処理を開始 (アダプタ除去およびペア相互訂正)",
            [メッセージID.エラー訂正開始] = "アセンブリ前のリードエラー訂正を開始",
            [メッセージID.開発中] = "開発中機能です",
            [メッセージID.コンティグ総延長] = "コンティグ総延長: {0}",
            [メッセージID.リードファイルのパス] = "{0}",
            [メッセージID.試すk一覧] = "[Multi-k] 検証対象 k = {0}",
            [メッセージID.リード読込の進捗] = "[Debug] {0} 件のリードを読み込み完了",
            [メッセージID.リード1の読込開始] = "フォワードリードファイルを読み込み中",
            [メッセージID.単一リードの読込開始] = "リードファイルを読み込み中",
            [メッセージID.スキャフォールド候補辺数] = "[Info] スキャフォールド候補辺 (コンティグレベル、閾値前): {0}{1}",
            [メッセージID.理想本数モデルあり] = " (理想本数モデル使用可能)",
            [メッセージID.理想本数モデルなし] = " (理想本数モデル使用不可)",
            [メッセージID.Phred_ファイル間で不一致] = "[Warning] 2 つのリードファイル間で Phred オフセット推定値が不一致です (read1 -> {0}、read2 -> {1}) -- 指定値 -p {2} を維持します",
            [メッセージID.Phred_未確定] = "未確定",
            [メッセージID.kmer種類数] = "[Debug] 固有 k-mer 数: {0}",
            [メッセージID.採用kmer数] = "[Debug] 採用 k-mer 数: {0}",
            [メッセージID.アセンブリ不能] = "\n対象ゲノムが複雑すぎるため現在のアセンブリパラメータでは処理できません\nパラメータを再調整してください\n",
            [メッセージID.概要_説明] = "Tsumiki -- Genome Assembler",
            [メッセージID.概要_バージョン] = "バージョン: {0}",
            [メッセージID.ヘルプ_使い方] = "使用方法: tsumiki {0} <path> [{1} <path>] [options]",
            [メッセージID.ヘルプ節_入力] = "# 入力設定",
            [メッセージID.ヘルプ節_kmerと品質] = "# k-mer / 品質設定",
            [メッセージID.ヘルプ節_ペアエンド] = "# ペアエンド / スキャフォールディング設定",
            [メッセージID.ヘルプ節_前処理] = "# 前処理設定",
            [メッセージID.ヘルプ節_マルチk] = "# マルチ k アセンブリ設定",
            [メッセージID.ヘルプ節_反復の安全策] = "# 反復配列解析の安全策",
            [メッセージID.ヘルプ節_出力とその他] = "# 出力 / その他設定",
            [メッセージID.ヘルプ_リード1] = "フォワード側 fastq(.gz) のパス (必須。シングルエンド時も指定)",
            [メッセージID.ヘルプ_リード2] = "リバース側 fastq(.gz) のパス",
            [メッセージID.ヘルプ_曖昧塩基] = "リード内の曖昧塩基 (N 等) を許容 (デフォルト: false)",
            [メッセージID.ヘルプ_k長] = "k-mer 長。カンマ区切り (例: 31,63,95) で各値を試行し最良結果を保持。{0} と同等 (デフォルト: リード長から自動算出、上限 {1})",
            [メッセージID.ヘルプ_kmerカットオフ] = "信頼する最小 k-mer 出現頻度 (デフォルト: k-mer スペクトルから自動算出)",
            [メッセージID.ヘルプ_Phred] = "Phred スコア ASCII オフセット ({0}) (デフォルト: {1})",
            [メッセージID.ヘルプ_クオリティカットオフ] = "信頼する塩基クオリティの下限値 (デフォルト: {0})",
            [メッセージID.ヘルプ_メモリ予算] = "k-mer カウント用のメモリ割り当て上限 (例: 2G, 512M) (デフォルト: {0})",
            [メッセージID.ヘルプ_インサートサイズ] = "期待インサートサイズ (デフォルト: マップドペアから自動推定)",
            [メッセージID.ヘルプ_ペア結合閾値] = "スキャフォールド辺採用に必要な最小優勢比率 (デフォルト: {0})",
            [メッセージID.ヘルプ_ペア支持数閾値] = "短反復の解決に必要な最小リードペア支持数 (デフォルト: {0})",
            [メッセージID.ヘルプ_積極性モード] = "{0}/{1} のプリセット。完全性と正確性のトレードオフを制御 (デフォルト: {2})",
            [メッセージID.ヘルプ_前処理] = "アダプタ読み抜けの切断およびペア重なりによる低品質塩基の相互訂正を実行 (デフォルト: false)",
            [メッセージID.ヘルプ_エラー訂正] = "アセンブリ前に k-mer スペクトルに基づきリードエラーを訂正 (デフォルト: false)",
            [メッセージID.ヘルプ_マルチk] = "複数の k でアセンブリを行い最良結果を選択 (デフォルト: false、実行時間最大 {0} 倍)",
            [メッセージID.ヘルプ_引き継ぎなし] = "前の k の配列を次の k へ引き継がない (デフォルト: 引き継ぐ)",
            [メッセージID.ヘルプ_SuperRead] = "ペアエンドリードを橋渡しして合成ロングリードを構築し引き継ぐ (デフォルト: false)",
            [メッセージID.ヘルプ_マージ] = "最良 k で未連結の接合点へ他 k の配列を補填挿入 (デフォルト: false、誤アセンブリ増大の可能性あり)",
            [メッセージID.ヘルプ_反復rMer検証] = "短反復の複製前に生リードの r-mer 支持を必須化 (デフォルト: false)",
            [メッセージID.ヘルプ_局所アセンブリ] = "ギャップ両端のマップドリードを用いて未閉鎖ギャップを局所再構築。{0} より安全 (デフォルト: false)",
            [メッセージID.ヘルプ_GFA出力] = "Bandage 等の可視化ツール向けに GFA1 形式ファイル ({0}) を出力 (デフォルト: false)",
            [メッセージID.ヘルプ_一時ディレクトリ] = "作業ディレクトリ。最終成果物、k ごとのアセンブリ、中間ファイルを出力 (デフォルト: {0})",
            [メッセージID.ヘルプ_一時ディレクトリ削除] = "終了時に中間ファイルを削除し、最終成果物とログのみ保持 (デフォルト: 削除しない)",
            [メッセージID.ヘルプ_スレッド数] = "リード読み込みに使用するワーカー スレッド数 (デフォルト: 論理プロセッサ数)",
            [メッセージID.ヘルプ_言語] = "表示メッセージの言語設定 (デフォルト: {0})",
            [メッセージID.ヘルプ_バージョン] = "バージョン情報を表示して終了",
            [メッセージID.ヘルプ_ヘルプ] = "ヘルプメッセージを表示して終了",
            [メッセージID.引き継ぎの統合開始] = "前 k から引き継いだ配列 {0:N0} 本を統合中",
            [メッセージID.引き継ぎの統合進捗] = "[Carry-over] 統合進捗: {0:N0} / {1:N0} 本",
            [メッセージID.引き継ぎの準備開始] = "次 k への引き継ぎ配列を準備中",
            [メッセージID.引き継ぎの準備完了] = "[Carry-over] 次 k への引き継ぎ配列 {0:N0} 本の準備完了",
            [メッセージID.SuperRead橋渡し開始] = "[SuperRead] リードペアの橋渡しを実行中",
            [メッセージID.SuperRead橋渡し進捗] = "[SuperRead] 処理済み: {0:N0} ペア (うち架橋完了: {1:N0} ペア)",
            [メッセージID.ポリッシュ開始] = "[Polish] 最終アセンブリへのリード再マッピングを実行中",
            [メッセージID.ポリッシュの索引構築] = "[Polish] 配列 {0:N0} 本 ({1:N0} bp) のインデックスを構築中",
            [メッセージID.ポリッシュの種が無い] = "[Polish] アセンブリから有効な {0}-mer シードを抽出できないためポリッシュをスキップ",
            [メッセージID.ポリッシュのマッピング開始] = "[Polish] リードをマッピング中",
            [メッセージID.ポリッシュの深度中央値] = "[Polish] カバレッジ深度の中央値: {0:F1}x",
            [メッセージID.ポリッシュを行えず] = "[Polish] ポリッシュ対象の配列が存在しません",
            [メッセージID.ポリッシュのマッピング結果] = "[Polish] リード配置完了: {0:N0} 件 (棄却: {1:N0} 件)",
            [メッセージID.ポリッシュの訂正結果] = "[Polish] 全 {1:N0} 塩基中 {0:N0} 塩基を修正",
            [メッセージID.ポリッシュの深度不足] = "[Polish] 低深度領域: {0:N0} / {1:N0} 位置 ({2:F2}%)",
            [メッセージID.閉じ目の検証開始] = "[Closure] 環状配列 {0} 本の閉鎖部領域をまたぐリードを検証中 ({1}bp ウィンドウ)",
            [メッセージID.閉じ目_環状の配列が無い] = "[Closure] アセンブリ内に環状配列は検出されませんでした",
            [メッセージID.閉じ目を裏付けた] = "[Closure] {0} ({1:N0} bp): 閉鎖部をまたぐリード {2} 件を確認 (必要数: {3})",
            [メッセージID.閉じ目を裏付けられず] = "[Closure] {0} ({1:N0} bp): 閉鎖部をまたぐリード不足 ({2} 件 / 必要数: {3})",
            [メッセージID.検査項目_グラフ被覆] = "グラフ被覆率",
            [メッセージID.検査項目_コピー数整合] = "コピー数整合性",
            [メッセージID.検査項目_深度の連続性] = "深度連続性",
            [メッセージID.検査項目_未解決のギャップ] = "未解決ギャップ",
            [メッセージID.検査項目_接合点の支持] = "接合点リード支持",
            [メッセージID.検査項目_競合経路] = "競合経路の有無",
            [メッセージID.検査項目_環状閉鎖] = "環状構造閉鎖",
            [メッセージID.検査判定_合格] = "合格",
            [メッセージID.検査判定_不合格] = "不合格",
            [メッセージID.検査判定_判定不能] = "判定不能",
            [メッセージID.完全性の見出し] = "[Complete] 完全性検証結果:",
            [メッセージID.完全性の検査行] = "[Complete]   {0}: {1} {2}",
            [メッセージID.完全長と判定] = "[Complete] 完全長 (Q{0})",
            [メッセージID.完全長に届かず] = "[Complete] 未完全 (Q{0})",
            [メッセージID.完全性の未達理由] = "[Complete] 未到達理由: {0}",
            [メッセージID.救済kmerの開始] = "[Mercy] リード内で信頼 k-mer に挟まれた閾値未満 k-mer の救済処理を実行中",
            [メッセージID.救済_対象外のk長] = "[Mercy] k={0} は 64 を超えるため救済処理の対象外です",
            [メッセージID.救済したkmer数] = "[Mercy] 候補 {1:N0} 個中 {0:N0} 個の k-mer を救済",
            [メッセージID.レポートを書き出した] = "[Report] {0} を出力完了",
            [メッセージID.曖昧箇所を書き出した] = "[Report] 曖昧箇所 {0:N0} 箇所を {1} に出力完了",
            [メッセージID.再開_中間ファイルを再利用] = "[Resume] {0} を再利用中",
            [メッセージID.ヘルプ節_完全性の検証] = "# 完全性検証設定",
            [メッセージID.ヘルプ_ポリッシュ] = "最終アセンブリにリードを再割り当てし、多数決で置換エラーを修復 (デフォルト: false)",
            [メッセージID.ヘルプ_環状閉鎖検証] = "閉鎖部をまたぐリード支持がある場合のみ環状構造として判定 (デフォルト: false)",
            [メッセージID.ヘルプ_救済kmer] = "リード内で信頼 k-mer に挟まれた閾値未満の k-mer を救済 (デフォルト: false)",
            [メッセージID.ヘルプ_再開] = "作業ディレクトリに残された前処理済み・エラー訂正済みリードを再利用 (デフォルト: false)",
            [メッセージID.ヘルプ_レポートの説明] = "{0} および {1} はアセンブリ生成時に常時出力されます",
            [メッセージID.分岐のない閉路] = "[Info] 通常のエントリ条件で取得できない分岐のない閉路 {0} 個を回収",
            [メッセージID.孤立した環状の複製単位] = "[Info] 単独で閉環するレプリコン {0} 個を端末間接続で連結",
            [メッセージID.ヘルプ_ログ水準] = "コンソールへのログ出力詳細度 (デフォルト: {0})。一時ディレクトリの {1} には常時全ログを保存",
            [メッセージID.ログの保存先] = "[Info] 詳細ログの保存先: {0}",
            [メッセージID.短すぎる閉路] = "[Debug] {1}bp 未満の閉路 {0} 個を無視 (単一塩基リピートや短鎖タンデムリピート由来アーティファクト)",
            [メッセージID.合成リードを再利用] = "[SuperRead] 初期 k で構築した合成リード {0:N0} 本を再利用中",
        };

        /// <summary>
        /// 中国語
        /// </summary>
        private static readonly Dictionary<メッセージID, string> _中国語 = new()
        {
            [メッセージID.デブルーイングラフの要約] = "[Debug] 精确 de Bruijn unitig 图：{0} 条有向边，{1} 个分支顶点 / 共 {2} 个顶点",
            [メッセージID.先読みで解決した分岐数] = "[Debug] 束搜索前瞻额外解决 {0} 处单步互唯一性无法确定的连接点",
            [メッセージID.GFA出力完了] = "[Info] 已将 unitig 图写入 {0} (GFA1)",
            [メッセージID.分岐選択の重み内訳] = "[Debug] 分支选择权重：单端 read 相邻 {0} 对 + 双端 read {1} 对",
            [メッセージID.単純化の収束] = "[Debug] 图简化在第 {0} 轮收敛",
            [メッセージID.単純化の打ち切り] = "[Debug] 图简化达到轮数上限 ({0}) 未完全收敛即停止",
            [メッセージID.バブル除去数] = "[Debug] 共移除 {0} 条简单气泡分支 (序列本身保留为独立 contig，仅移除图中的边)",
            [メッセージID.反復解決数] = "[Debug] 重复解析：借助跨越 reads 对，共复制并解缠 {0} 处短重复 (<= {1}bp)",
            [メッセージID.辺選択の内訳] = "[Debug] 边选择：单出边顶点 {0} 个，凭 read 支持解决的分支 {1} 个，因来自多拷贝重复而未解决的分支 {2} 个 (重复内部 read 无法区分各拷贝)",
            [メッセージID.反復通り抜けで棄却した結合数] = "[Debug] 拒绝 {0} 处穿过未解缠多拷贝重复的连接 (穿过会导致拷贝间序列缺失)",
            [メッセージID.相互一意で残った結合数] = "[Debug] 通过互唯一性检查的有向合并：{0} 处 (无向换算：{1} 处)",
            [メッセージID.環状コンティグあり] = "[Info] 闭合成环的 contig：{0} 条 ({1}) -- 表示复制子 (染色体或质粒) 已完整组装",
            [メッセージID.環状コンティグなし] = "[Info] 未发现闭合环状 contig (所有复制子仍处于片段状态)",
            [メッセージID.確定辺標本数] = "[Info] 来自已确定 unitig 相邻关系的插入片段长度样本：{0} 个",
            [メッセージID.確定辺標本の中央値] = "[Info] 已确定边样本中位数：{0} (样本数：{1}，不受同一 unitig 样本长度偏差影响)",
            [メッセージID.短すぎるユニティグの除外] = "[Warning] 比对时已跳过 {0} 条短于 k-mer 长度的 unitig",
            [メッセージID.曖昧なkmer登録] = "[Warning] 比对时已忽略 {0} 处多条 unitig 共享的歧义 k-mer 登记",
            [メッセージID.ペア隣接候補数] = "[Info] 双端相邻候选：{0} 条边 (共 {1} 对支持 reads 对)",
            [メッセージID.同一ユニティグのペア向き集計] = "[Info] 同一 unitig 内 read 对方向：同向 {0} 个，反向 {1} 个 -- 采用 '{2}' 作为文库观测方向估计插入片段长度 (样本数：{3})",
            [メッセージID.同一ユニティグの断片長分布] = "[Info] 同一 unitig 内片段长度分布：{0}",
            [メッセージID.同一ユニティグの断片長中央値] = "[Info] 同一 unitig 内片段长度中位数：{0} (样本数：{1}，包含 read 长度的真实片段长度；若 unitig 短于真实插入片段则可能偏小)",
            [メッセージID.ペアリードIDの不一致] = "[Warning] 此处配对 read ID 不匹配 (\"{0}\" vs \"{1}\") -- 此后的双端相邻检测可靠性可能降低 (单端检测不受影响)",
            [メッセージID.統合できる接合点なし] = "[Merge] 无其他 k 能够跨越骨架连接点，保持原组装不变",
            [メッセージID.統合した接合点数] = "[Merge] 使用其他 k 的序列连接了 {0} 处骨架连接点",
            [メッセージID.候補一覧の見出し] = "[Multi-k] 候选组装评估 (基于公共锚定 k-mer 集合)：",
            [メッセージID.候補一覧の明細] = "[Multi-k]   k={0,3}: {1}{2}",
            [メッセージID.統計_ファイルなし] = "[Stats] {0}: (未找到文件：{1})",
            [メッセージID.統計] = "[Stats] {0}: {1}",
            [メッセージID.統計_長さで絞り込み] = "[Stats] {0} (>={1}bp，符合 abyss-fac 对比条件)：{2}",
            [メッセージID.検査_対象外のk長] = "[Check] {0}: 已跳过 (自检功能仅支持 k <= 64)",
            [メッセージID.検査_取りこぼし] = "[Check] {0}: 可信 k-mer 共 {1:N0} 个，其中 {2:N0} 个 ({3:0.00}%) 未在组装中出现 (被修剪或未到达的序列)",
            [メッセージID.検査_出しすぎ] = "[Check] {0}: 组装中 k-mer 实例共 {1:N0} 个，其中 {2:N0} 个 ({3:0.00}%) 超出覆盖度支持的拷贝数 (涉及 {4:N0} 种 k-mer，导致总长度虚增)",
            [メッセージID.kmerインデックス構築開始] = "开始构建 k-mer 索引",
            [メッセージID.kmerカットオフ適用] = "正在应用 k-mer 截断阈值",
            [メッセージID.引き継ぎで追加したkmer数] = "[Carry-over] 从上一个 k 补充当前 k 未观测到的 k-mer {0:N0} 个",
            [メッセージID.tip除去開始] = "正在修剪短 tip",
            [メッセージID.ユニティグ構築開始] = "开始构建 unitig",
            [メッセージID.グラフが複雑すぎる] = "[Warning] k={0} 时图结构过于复杂 (unitig 数量超过上限 {1})，跳过该 k",
            [メッセージID.リードのマッピング開始] = "开始将 reads 比对到 unitig",
            [メッセージID.ユニティグ結合開始] = "开始合并 unitig",
            [メッセージID.rMer検証の見送り] = "[Info] k={0} 时跳过重复 r-mer 验证：所需的 r-mer 长度 ({1}bp) 超过 32bp 打包上限",
            [メッセージID.コンティグ構築完了] = "contig 构建完成",
            [メッセージID.スキャフォールディング開始] = "开始对 contig 进行 scaffolding",
            [メッセージID.ギャップ充填開始] = "开始填补 scaffold ギャップ",
            [メッセージID.kが薄すぎて省略] = "[Multi-k] 跳过 k={0}：预测 k-mer 覆盖度 {1:F1}x 低于阈值 {2:F1}x，无法生成可用图",
            [メッセージID.kの開始見出し] = "[Multi-k] ===== 开始使用 k={0} 进行组装 =====",
            [メッセージID.kでアセンブリできず] = "[Multi-k] k={0} 未能生成组装结果，跳过该 k",
            [メッセージID.単一のkのみ成功] = "[Multi-k] 仅有一个 k 成功生成组装，无需比较直接采用",
            [メッセージID.アンカーkmer集合の構築] = "[Multi-k] 正在构建用于比较的公共锚定 k-mer 集合 (k={0})",
            [メッセージID.アンカースペクトルが二峰でない] = "[Multi-k] 锚定 k-mer 谱未显示双峰特征，无法比较候选组装",
            [メッセージID.候補を評価できない] = "[Multi-k] 无法评估候选组装，回退到最大 k 的结果",
            [メッセージID.採用したk] = "[Multi-k] 已选择 k={0}",
            [メッセージID.統合開始] = "[Merge] 正在将其他 k 的序列合并到选定的组装中",
            [メッセージID.統合結果を評価できない] = "[Merge] 无法评估合并结果，保留原选定的组装",
            [メッセージID.統合前の評価] = "[Merge]   合并前：{0}",
            [メッセージID.統合後の評価] = "[Merge]   合并后：{0}",
            [メッセージID.統合が骨格に勝てず] = "[Merge] 合并结果未优于原选定组装，保持原样",
            [メッセージID.統合結果を採用] = "[Merge] 已采用合并后的组装结果",
            [メッセージID.エラー訂正_スペクトル構築] = "[ErrorCorrection] 正在构建 k-mer 谱...",
            [メッセージID.エラー訂正_訂正開始] = "[ErrorCorrection] 正在对 reads 进行纠错...",
            [メッセージID.エラー訂正_ファイル別統計] = "[ErrorCorrection] {0}: 已校正 {1}/{2} 条 reads (共纠错 {3} 个碱基)",
            [メッセージID.リード読込完了] = "已从 {1} 读取 {0} 条 reads",
            [メッセージID.リード2の読込開始] = "正在读取反向 reads 文件",
            [メッセージID.前処理統計] = "[Preprocess] {1} 对中有 {0} 对检测到接头读通并修剪 (共相互校正 {2} 个碱基)",
            [メッセージID.SuperRead統計] = "[SuperRead] {1} 对中有 {0} 对桥接为合成 long read 并传递到下一个 k",
            [メッセージID.SuperRead統計_重なり] = "[SuperRead] 桥接细分：{0} 对通过直接重叠连接，{1} 对通过图路径连接",
            [メッセージID.SuperRead統計_曖昧] = "[SuperRead] {0} 对重叠位置歧义的 read 对已移交图搜索处理 (重复序列匹配多处)",
            [メッセージID.短い配列を除外] = "[Info] 已从最终结果中剔除 {0} 条短于 {1}bp 的序列 (共 {2}bp，已在工作目录中保留)",
            [メッセージID.最終成果物] = "[Info] 最终组装：{0} (unitigs/contigs/scaffolds 代表合并、过滤和打磨前的阶段性产物)",
            [メッセージID.ギャップ充填_対象なし] = "[Info] ギャップ填补：没有需要填补的ギャップ",
            [メッセージID.ギャップ充填統計] = "[Info] ギャップ填补：{1} 处中有 {0} 处已用真实序列填补 (替换 {2:N0}bp 的 N)；{3} 处因多条路径、{4} 处因无连接路径而保留为 N",
            [メッセージID.局所アセンブリ_対象なし] = "[Info] 局部组装：没有符合条件的剩余ギャップ",
            [メッセージID.局所アセンブリ統計] = "[Info] 局部组装：剩余 {1} 处中有 {0} 处通过局部重组 reads 填补 (替换 {2:N0}bp 的 N)；{3} 处缺乏 reads，{4} 处多条路径，{5} 处无连接路径",
            [メッセージID.スキャフォールディング省略_インサートサイズ不明] = "[Info] 跳过 scaffolding：未指定插入片段长度且无法从比对 read 对中估计",
            [メッセージID.スキャフォールディング開始_インサートサイズ] = "[Info] 以插入片段长度 {0} 开始 scaffolding",
            [メッセージID.スキャフォールディング省略_コンティグなし] = "[Info] 跳过 scaffolding：未找到 contig",
            [メッセージID.内部を指したペア候補] = "[Info] 已跳过 {0} 个指向已连接 contig 内部 unitig 的双端候选 (端点已在 contig 构建时解决)",
            [メッセージID.未配置を指したペア候補] = "[Info] 已跳过 {0} 个指向未放置到任何 contig 中的 unitig 的双端候选 (如过短)",
            [メッセージID.閾値後のスキャフォールド辺] = "[Info] 阈值处理后确定的 scaffold 边：{0} 条 (互唯一性检查拒绝 {1} 条，保留 {2} 条)",
            [メッセージID.スキャフォールド出力完了] = "[Info] 已将 {0} 条 scaffold (总长 {1}) 写入 {2}",
            [メッセージID.インサートサイズ推定_同一ユニティグ] = "[Info] 根据 {1} 对同一 unitig 样本将插入片段长度估计为 {0} (中位数；unitig N50 {2} >= 估计值的 {3} 倍，不受截断偏差影响)",
            [メッセージID.インサートサイズ推定_確定辺] = "[Info] 根据 {1} 对已确定边样本将插入片段长度估计为 {0} (中位数；因 unitig 长度限制优先于同一 unitig 样本)",
            [メッセージID.インサートサイズ推定_標本不足] = "[Info] 自动估计插入片段长度需要至少 {0} 个样本 (仅收集到已确定边样本 {1} 个，总计 {2} 个)",
            [メッセージID.インサートサイズ推定_全標本] = "[Info] 根据 {1} 对全样本将插入片段长度估计为 {0} (中位数；因已确定边样本不足 ({2} 个) 回退到全样本，可能偏小)",
            [メッセージID.単一コピー基準値] = "[Info] 单拷贝覆盖度基线估计值：{0:0.#} (长度加权中位数)",
            [メッセージID.コピー数の要約] = "[Info] 估计拷贝数：{0}",
            [メッセージID.反復配列の割合] = "[Info] 多拷贝 (重复) 序列含量：{0:N0}bp / {1:N0}bp (占组装结果的 {2:0.0}%)",
            [メッセージID.グラフ単純化の反復] = "[GraphSimplifier] 迭代 {0}：评估了 {1} 条 unitig (tip 阈值 < {2}bp，基线覆盖度 {3:0.#})；移除 {4} 条 tip，从 {6} 条边修剪了 {5} 个低覆盖度 k-mer",
            [メッセージID.rMer検証による棄却] = "[Debug] r-mer 验证否决了 {0} 处缺乏跨越 reads 支持的重复复制",
            [メッセージID.例外を無視_見出し] = "[Warning] 将忽略以下异常并继续运行：",
            [メッセージID.例外を無視_メソッド] = "          方法：{0}",
            [メッセージID.停止_見出し] = "[Error] 程序运行已停止：",
            [メッセージID.停止_メソッド] = "        方法：{0}",
            [メッセージID.タイムスタンプ] = "[Log] {0:yyyy/MM/dd HH:mm:ss}",
            [メッセージID.Phred_明示指定と不一致] = "[Warning] 质量格式看起来像 Phred{0}，但显式指定了 -p {1}；优先采用显式指定值 (若数据确为 Phred{3}，请使用 -p {2} 重新运行)",
            [メッセージID.Phred_自動判定] = "[Info] 根据质量字符串自动判定 Phred 偏移为 {0} (观测 ASCII 范围：[{1}, {2}])；显式指定 -p 可覆盖此设置",
            [メッセージID.Phred_検査の警告] = "[Warning] {0} 的 Phred 编码检查警告：{1}",
            [メッセージID.kmerカットオフ_混合モデル] = "[Info] 通过双成分混合模型自动选择 k-mer 截断阈值为 {0} (单拷贝均值：{1:0.#}，可信下限：{2}，EM 迭代：{3} 次)；显式指定 -kc 可覆盖",
            [メッセージID.kmerカットオフ_谷が不明] = "[Info] 无法识别明确的直方图谷值 (可能缺乏双峰特征)，保持 -kc {0}",
            [メッセージID.kmerカットオフ_スペクトル] = "[Info] 根据 k-mer 谱自动选择 k-mer 截断阈值为 {0}；显式指定 -kc 可覆盖",
            [メッセージID.kmerヒストグラム] = "[Info] k-mer 频数直方图 (出现次数: 独特 k-mer 数)：{0}",
            [メッセージID.スペクトルの谷が不明] = "[Info] 无法识别明确的直方图谷值 (在此覆盖度下 k-mer 谱可能不呈现双峰)",
            [メッセージID.スペクトルの谷とピーク] = "[Info] k-mer 谱：谷值位于频数 {0} ({1} 种)，单拷贝峰值位于频数 {2} ({3} 种)",
            [メッセージID.ゲノムサイズとカバレッジの推定] = "[Info] 估计基因组大小：{0:N0} bp，估计覆盖度：{1}",
            [メッセージID.k自動選択_リード長不明] = "[Info] 无法采样获得 read 长度，保持 -k {0}",
            [メッセージID.k自動選択_kが長すぎる] = "[Warning] 指定的 -k {0} 不短于观测 read 长度 ({1} bp)，无法提取 k-mer；请调小 -k 值",
            [メッセージID.k自動選択_リード長が短い] = "[Info] 观测 read 长度 ({0} bp) 过短，无法自动选择 k，保持 -k {1}",
            [メッセージID.k自動選択] = "[Info] 根据观测 read 长度 ({1} bp) 自动选择 k={0}；显式指定 -k 可覆盖",
            [メッセージID.開始kmerの探索] = "[Debug] 正在搜索起始 k-mer",
            [メッセージID.一時ディレクトリを残した] = "[Info] 结果与中间文件已保留在 {0} 中 (使用 {1} 可删除中间文件)",
            [メッセージID.中間ファイルを削除した] = "[Info] 已删除 {0} 中的中间文件 (最终结果与日志已保留)",
            [メッセージID.支持検査の開始] = "[Check] 正在验证最终组装中每个 {0}-mer 的 read 支持",
            [メッセージID.支持検査の結果] = "[Check] Read 支持率 ({0}-mer)：全 {2} 个位置中有 {1} 个 ({3}%) 未在 reads 中出现 (共 {4} 处非支持区间)",
            [メッセージID.支持のない箇所を書き出した] = "[Check] 已将 {0} 处无支持区间写入 {1}",
            [メッセージID.検査項目_リードの支持] = "read 支持率",
            [メッセージID.リード長の観測値] = "[Info] 观测 read 长度 (采样中位数)：{0} bp",
            [メッセージID.一時ディレクトリが既にある] = "目录 {0} 已存在",
            [メッセージID.パスの確認] = "请检查指定的路径",
            [メッセージID.前処理省略_ペアなし] = "[Warning] -pp 选项需要双端 reads (未指定 read2)，跳过预处理",
            [メッセージID.前処理開始] = "正在对 reads 进行预処理 (去接头与配对互校正)",
            [メッセージID.エラー訂正開始] = "组装前正在对 reads 进行纠错",
            [メッセージID.開発中] = "功能正在开发中",
            [メッセージID.コンティグ総延長] = "contig 总长度：{0}",
            [メッセージID.リードファイルのパス] = "{0}",
            [メッセージID.試すk一覧] = "[Multi-k] 尝试 k = {0}",
            [メッセージID.リード読込の進捗] = "[Debug] 已读取 {0} 条 reads",
            [メッセージID.リード1の読込開始] = "正在读取正向 reads 文件",
            [メッセージID.単一リードの読込開始] = "正在读取 reads 文件",
            [メッセージID.スキャフォールド候補辺数] = "[Info] scaffold 候选边 (contig 级，阈值处理前)：{0}{1}",
            [メッセージID.理想本数モデルあり] = " (理想计数模型可用)",
            [メッセージID.理想本数モデルなし] = " (理想计数模型不可用)",
            [メッセージID.Phred_ファイル間で不一致] = "[Warning] 两个 reads 文件推断出的 Phred 偏移不一致 (read1 -> {0}，read2 -> {1})；保持 -p {2} 不变",
            [メッセージID.Phred_未確定] = "未确定",
            [メッセージID.kmer種類数] = "[Debug] 独特 k-mer 数：{0}",
            [メッセージID.採用kmer数] = "[Debug] 保留 k-mer 数：{0}",
            [メッセージID.アセンブリ不能] = "\n目标基因组过复杂，无法在当前参数下组装\n请调整参数\n",
            [メッセージID.概要_説明] = "Tsumiki -- 基因组组装工具",
            [メッセージID.概要_バージョン] = "版本：{0}",
            [メッセージID.ヘルプ_使い方] = "用法：tsumiki {0} <path> [{1} <path>] [options]",
            [メッセージID.ヘルプ節_入力] = "# 输入设置",
            [メッセージID.ヘルプ節_kmerと品質] = "# k-mer / 质量设置",
            [メッセージID.ヘルプ節_ペアエンド] = "# 双端 / Scaffolding 设置",
            [メッセージID.ヘルプ節_前処理] = "# 预处理设置",
            [メッセージID.ヘルプ節_マルチk] = "# 多 k 组装设置",
            [メッセージID.ヘルプ節_反復の安全策] = "# 重复序列解析安全措施",
            [メッセージID.ヘルプ節_出力とその他] = "# 输出 / 其他设置",
            [メッセージID.ヘルプ_リード1] = "正向 fastq(.gz) 路径 (必填；单端 reads 也使用此项)",
            [メッセージID.ヘルプ_リード2] = "反向 fastq(.gz) 路径",
            [メッセージID.ヘルプ_曖昧塩基] = "允许 reads 中包含模糊碱基 (如 N) (默认：false)",
            [メッセージID.ヘルプ_k長] = "k-mer 长度；逗号分隔列表 (如 31,63,95) 将尝试每个值并保留最佳结果，等同于 {0} (默认：根据 read 长度自动计算，上限 {1})",
            [メッセージID.ヘルプ_kmerカットオフ] = "可信 k-mer 的最小出现频数 (默认：根据 k-mer 谱自动计算)",
            [メッセージID.ヘルプ_Phred] = "Phred 分数 ASCII 偏移量 ({0}) (默认：{1})",
            [メッセージID.ヘルプ_クオリティカットオフ] = "可信碱基质量下限值 (默认：{0})",
            [メッセージID.ヘルプ_メモリ予算] = "k-mer 计数内存上限，如 2G、512M (默认：{0})",
            [メッセージID.ヘルプ_インサートサイズ] = "期望插入片段长度 (默认：从比对 read 对中自动估计)",
            [メッセージID.ヘルプ_ペア結合閾値] = "接受 scaffold 边所需的最小优势比例 (默认：{0})",
            [メッセージID.ヘルプ_ペア支持数閾値] = "解决短重复所需的最小 reads 对支持数 (默认：{0})",
            [メッセージID.ヘルプ_積極性モード] = "{0}/{1} 的预设值，平衡完整性与准确性 (默认：{2})",
            [メッセージID.ヘルプ_前処理] = "修剪接头读通部分，并利用配对重叠相互校正低质量碱基 (默认：false)",
            [メッセージID.ヘルプ_エラー訂正] = "组装前根据 k-mer 谱校正 reads 错误 (默认：false)",
            [メッセージID.ヘルプ_マルチk] = "使用多个 k 进行组装并保留最佳结果 (默认：false；运行时间增加最多 {0} 倍)",
            [メッセージID.ヘルプ_引き継ぎなし] = "不在 k 迭代之间传递序列 (默认：传递)",
            [メッセージID.ヘルプ_SuperRead] = "将双端 reads 桥接为合成 long reads 并予以传递 (默认：false)",
            [メッセージID.ヘルプ_マージ] = "将其他 k 的序列拼接填充到未解决的骨架连接点 (默认：false；可能增加错误组装)",
            [メッセージID.ヘルプ_反復rMer検証] = "复制短重复前要求原始 reads 的 r-mer 支持 (默认：false)",
            [メッセージID.ヘルプ_局所アセンブリ] = "使用比对到ギャップ两侧的 reads 局部重组未闭合的ギャップ；比 {0} 更安全 (默认：false)",
            [メッセージID.ヘルプ_GFA出力] = "导出 GFA1 格式文件 ({0}) 以供 Bandage 等可视化工具使用 (默认：false)",
            [メッセージID.ヘルプ_一時ディレクトリ] = "工作目录，用于存放最终结果、各 k 的组装及中间文件 (默认：{0})",
            [メッセージID.ヘルプ_一時ディレクトリ削除] = "运行完成后删除中间文件，仅保留最终结果和日志 (默认：不删除)",
            [メッセージID.ヘルプ_スレッド数] = "用于读取 reads 的工作线程数 (默认：逻辑处理器数)",
            [メッセージID.ヘルプ_言語] = "消息显示语言 (默认：{0})",
            [メッセージID.ヘルプ_バージョン] = "显示版本信息并退出",
            [メッセージID.ヘルプ_ヘルプ] = "显示此帮助信息并退出",
            [メッセージID.引き継ぎの統合開始] = "正在合并从上一个 k 传递来的 {0:N0} 条序列",
            [メッセージID.引き継ぎの統合進捗] = "[Carry-over] 合并进度：{0:N0} / {1:N0} 条",
            [メッセージID.引き継ぎの準備開始] = "正在准备传递给下一个 k 的序列",
            [メッセージID.引き継ぎの準備完了] = "[Carry-over] 已为下一个 k 准备序列 {0:N0} 条",
            [メッセージID.SuperRead橋渡し開始] = "[SuperRead] 正在桥接 read 对",
            [メッセージID.SuperRead橋渡し進捗] = "[SuperRead] 已处理 {0:N0} 对 (其中 bridge 成功 {1:N0} 对)",
            [メッセージID.ポリッシュ開始] = "[Polish] 正在将 reads 重新比对到最终组装结果",
            [メッセージID.ポリッシュの索引構築] = "[Polish] 正在索引 {0:N0} 条序列 ({1:N0} bp)",
            [メッセージID.ポリッシュの種が無い] = "[Polish] 无法提取有效的 {0}-mer 种子，跳过 polish 步骤",
            [メッセージID.ポリッシュのマッピング開始] = "[Polish] 正在比对 reads",
            [メッセージID.ポリッシュの深度中央値] = "[Polish] 覆盖深度中位数：{0:F1}x",
            [メッセージID.ポリッシュを行えず] = "[Polish] 无可打磨的对象",
            [メッセージID.ポリッシュのマッピング結果] = "[Polish] 已放置 reads {0:N0} 条 (舍弃 {1:N0} 条)",
            [メッセージID.ポリッシュの訂正結果] = "[Polish] 已在全 {1:N0} 个碱基中修正 {0:N0} 个",
            [メッセージID.ポリッシュの深度不足] = "[Polish] 低深度位置：{0:N0} / {1:N0} ({2:F2}%)",
            [メッセージID.閉じ目の検証開始] = "[Closure] 正在验证跨越 {0} 条环状序列闭合处的 reads ({1}bp 窗口)",
            [メッセージID.閉じ目_環状の配列が無い] = "[Closure] 组装结果中未检测到闭合环状序列",
            [メッセージID.閉じ目を裏付けた] = "[Closure] {0} ({1:N0} bp)：确认跨越闭合处的 reads {2} 条 (需要：{3} 条)",
            [メッセージID.閉じ目を裏付けられず] = "[Closure] {0} ({1:N0} bp)：跨越闭合处的 reads 不足 ({2} 条 / 需要：{3} 条)",
            [メッセージID.検査項目_グラフ被覆] = "图覆盖率",
            [メッセージID.検査項目_コピー数整合] = "拷贝数一致性",
            [メッセージID.検査項目_深度の連続性] = "深度连续性",
            [メッセージID.検査項目_未解決のギャップ] = "未解决ギャップ",
            [メッセージID.検査項目_接合点の支持] = "接合点 read 支持",
            [メッセージID.検査項目_競合経路] = "竞争路径",
            [メッセージID.検査項目_環状閉鎖] = "环状闭合",
            [メッセージID.検査判定_合格] = "PASS",
            [メッセージID.検査判定_不合格] = "FAIL",
            [メッセージID.検査判定_判定不能] = "UNKNOWN",
            [メッセージID.完全性の見出し] = "[Complete] 完整性检查结果：",
            [メッセージID.完全性の検査行] = "[Complete]   {0}: {1} {2}",
            [メッセージID.完全長と判定] = "[Complete] 完整 (Q{0})",
            [メッセージID.完全長に届かず] = "[Complete] 未完全 (Q{0})",
            [メッセージID.完全性の未達理由] = "[Complete] 未达到原因：{0}",
            [メッセージID.救済kmerの開始] = "[Mercy] 正在救回在 reads 内位于可信 k-mer 之间的截断值以下 k-mer",
            [メッセージID.救済_対象外のk長] = "[Mercy] k={0} 超过 64，救回算法不可用",
            [メッセージID.救済したkmer数] = "[Mercy] 已在 {1:N0} 个候选中救回 {0:N0} 个 k-mer",
            [メッセージID.レポートを書き出した] = "[Report] 已生成 {0}",
            [メッセージID.曖昧箇所を書き出した] = "[Report] 已将 {0:N0} 处歧义位置写入 {1}",
            [メッセージID.再開_中間ファイルを再利用] = "[Resume] 复用 {0}",
            [メッセージID.ヘルプ節_完全性の検証] = "# 完整性检查设置",
            [メッセージID.ヘルプ_ポリッシュ] = "将 reads 重新比对到最终组装，按多数表决修复替换错误 (默认：false)",
            [メッセージID.ヘルプ_環状閉鎖検証] = "仅在存在跨越闭合处的 reads 支持时判定为环状 (默认：false)",
            [メッセージID.ヘルプ_救済kmer] = "救回 reads 内位于可信 k-mer 之间的截断值以下 k-mer (默认：false)",
            [メッセージID.ヘルプ_再開] = "复用工作目录中已有的预处理和纠错后 reads (默认：false)",
            [メッセージID.ヘルプ_レポートの説明] = "{0} 与 {1} 将始终在生成组装时自动写出",
            [メッセージID.分岐のない閉路] = "[Info] 已找回常规入口条件未覆盖的无分支闭环 {0} 个",
            [メッセージID.孤立した環状の複製単位] = "[Info] 已首尾相连闭合 {0} 个独立闭环的复制单元",
            [メッセージID.ヘルプ_ログ水準] = "控制台日志详细程度 (默认：{0})；临时目录中的 {1} 始终保留完整日志",
            [メッセージID.ログの保存先] = "[Info] 完整运行日志保存于 {0}",
            [メッセージID.短すぎる閉路] = "[Debug] 已忽略短于 {1}bp 的闭环 {0} 个 (可能源自单碱基或短串联重复伪影)",
            [メッセージID.合成リードを再利用] = "[SuperRead] 正在复用在初始 k 构建的合成 reads {0:N0} 条",
        };

        #endregion

        #region 公開メソッド

        /// <summary>
        /// p_ID の書式文字列
        /// </summary>
        /// <param name="p_言語"></param>
        /// <param name="p_ID"></param>
        /// <remarks>
        /// 指定言語に無ければ英語を返す
        /// </remarks>
        /// <returns></returns>
        public static string Get_書式(言語 p_言語, メッセージID p_ID)
        {
            var l_辞書 = Get_辞書(p_言語);
            return l_辞書 is not null && l_辞書.TryGetValue(p_ID, out var l_書式) ? l_書式 : _英語.TryGetValue(p_ID, out var l_英語) ? l_英語 : p_ID.ToString();
        }

        #endregion

        #region テストメソッド

        /// <summary>
        /// その言語にこの ID の訳があるか
        /// </summary>
        /// <param name="p_言語"></param>
        /// <param name="p_ID"></param>
        /// <remarks>
        /// 訳の入れ忘れの検査に使う
        /// </remarks>
        /// <returns></returns>
        public static bool Has訳(言語 p_言語, メッセージID p_ID)
        {
            return Get_辞書(p_言語)?.ContainsKey(p_ID) == true;
        }

        #endregion

        #region 内部メソッド

        /// <summary>
        /// その言語の辞書
        /// </summary>
        /// <param name="p_言語"></param>
        /// <remarks>
        /// まだ用意していない言語は null
        /// </remarks>
        /// <returns></returns>
        private static Dictionary<メッセージID, string>? Get_辞書(言語 p_言語)
        {
            return p_言語 switch
            {
                言語.英語 => _英語,
                言語.日本語 => _日本語,
                言語.中国語 => _中国語,
                _ => null,
            };
        }

        #endregion
    }
}
